[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrbd_utils"
version = "0.1.0"
description = "Utilities for PyRBD Suite"
requires-python = ">=3.7"
dependencies = [
    "networkx",
    "pandas",
    "tqdm",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["src"]
