[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrbd_plusplus"
version = "0.1.0"
description = "PyRBD PlusPlus"
requires-python = ">=3.7"
dependencies = [
    "pyrbd_utils",
    "numpy", 
]

[tool.setuptools.packages.find]
where = ["src"]
